// js2rust-bridge: Rust FFI bindings for translated JS/Zig code.
//
// AUTO-GENERATED by js2rustc — do not edit manually.
// Each `js2rust_bridge!()` invocation reads cabi_exports.json at compile time
// and generates `unsafe extern "C"` + safe Rust wrappers.

use js2rust_bridge_macro::js2rust_bridge;

pub mod host;

// === Auto-generated FFI bindings for each group ===
js2rust_bridge!("out/builtins/cabi_exports.json");
js2rust_bridge!("out/classes/cabi_exports.json");
js2rust_bridge!("out/main/cabi_exports.json");

// === String conversion helpers ===

/// Convert a null-terminated C string pointer to a Rust &str.
///
/// # Safety
/// The pointer must be a valid, null-terminated C string allocated by Zig.
/// The returned &str borrows the memory; call the corresponding `free_*`
/// function after use to release the memory.
pub unsafe fn cstr_to_str<'a>(ptr: *const std::ffi::c_char) -> Option<&'a str> {
    if ptr.is_null() {
        return None;
    }
    let c_str = unsafe { std::ffi::CStr::from_ptr(ptr) };
    c_str.to_str().ok()
}

// === Test groups: FFI bindings + tests (only compiled during `cargo test`) ===

#[cfg(test)]
#[allow(non_snake_case)]
mod generated_tests {
    use js2rust_bridge_macro::js2rust_bridge;

    // Re-import normal group wrappers
    #[allow(unused_imports)]
    use super::*;

    // Test group FFI bindings
    js2rust_bridge!("out/test_builtins_array/cabi_exports.json");
    js2rust_bridge!("out/test_builtins_math/cabi_exports.json");
    js2rust_bridge!("out/test_builtins_string/cabi_exports.json");
    js2rust_bridge!("out/test_cabi/cabi_exports.json");
    js2rust_bridge!("out/test_classes_adv/cabi_exports.json");
    js2rust_bridge!("out/test_closures/cabi_exports.json");
    js2rust_bridge!("out/test_control_flow/cabi_exports.json");
    js2rust_bridge!("out/test_expressions/cabi_exports.json");
    js2rust_bridge!("out/test_template/cabi_exports.json");
    js2rust_bridge!("out/test_types/cabi_exports.json");

    // === Auto-generated test functions ===

    // --- test_builtins_array ---
    #[test]
    fn test_arr_len() {
        assert_eq!(testArrLen_test_builtins_array(), 5);
    }

    #[test]
    fn test_arr_includes() {
        assert_eq!(testArrIncludes_test_builtins_array(), true);
    }

    #[test]
    fn test_arr_indexof() {
        assert_eq!(testArrIndexOf_test_builtins_array(), 1);
    }


    // --- test_builtins_math ---
    #[test]
    fn test_floor() {
        let _ = testMathFloor_test_builtins_math(3.7);
    }

    #[test]
    fn test_ceil() {
        let _ = testMathCeil_test_builtins_math(3.2);
    }

    #[test]
    fn test_round() {
        let _ = testMathRound_test_builtins_math(3.5);
    }

    #[test]
    fn test_sign_pos() {
        assert_eq!(testSign_test_builtins_math(42), 1);
    }

    #[test]
    fn test_sign_neg() {
        assert_eq!(testSign_test_builtins_math(-5), -1);
    }

    #[test]
    fn test_sign_zero() {
        assert_eq!(testSign_test_builtins_math(0), 0);
    }

    #[test]
    fn test_parse_int() {
        assert_eq!(testParseInt_test_builtins_math("42"), 42);
    }

    #[test]
    fn test_sqrt() {
        let _ = testSqrt_test_builtins_math(2.5);
    }

    #[test]
    fn test_abs() {
        let _ = testAbsF_test_builtins_math(-3.5);
    }

    #[test]
    fn test_pow() {
        let _ = testPow_test_builtins_math(2.5, 3.5);
    }


    // --- test_builtins_string ---
    #[test]
    fn test_includes_t() {
        assert_eq!(testIncludes_test_builtins_string(), true);
    }

    #[test]
    fn test_includes_f() {
        assert_eq!(testIncludesFalse_test_builtins_string(), false);
    }

    #[test]
    fn test_indexof_found() {
        assert_eq!(testIndexOf_test_builtins_string(), 6);
    }

    #[test]
    fn test_indexof_miss() {
        assert_eq!(testIndexOfMiss_test_builtins_string(), -1);
    }

    #[test]
    fn test_starts_t() {
        assert_eq!(testStartsWithTrue_test_builtins_string(), true);
    }

    #[test]
    fn test_starts_f() {
        assert_eq!(testStartsWithFalse_test_builtins_string(), false);
    }

    #[test]
    fn test_ends_t() {
        assert_eq!(testEndsWithTrue_test_builtins_string(), true);
    }

    #[test]
    fn test_ends_f() {
        assert_eq!(testEndsWithFalse_test_builtins_string(), false);
    }

    #[test]
    fn test_strlen() {
        assert_eq!(testStrLen_test_builtins_string(), 5);
    }


    // --- test_cabi ---
    #[test]
    fn test_cabi_add() {
        assert_eq!(cabiAdd_test_cabi(3, 5), 8);
    }

    #[test]
    fn test_cabi_pos() {
        assert_eq!(cabiIsPositive_test_cabi(5), true);
    }

    #[test]
    fn test_cabi_neg() {
        assert_eq!(cabiIsPositive_test_cabi(-3), false);
    }


    // --- test_classes_adv ---
    #[test]
    fn test_rect() {
        assert_eq!(testRect_test_classes_adv(), 12);
    }

    #[test]
    fn test_settings() {
        assert_eq!(testSettings_test_classes_adv(), 50);
    }

    #[test]
    fn test_counter() {
        assert_eq!(testCounter_test_classes_adv(), 100);
    }

    #[test]
    fn test_vec2() {
        assert_eq!(testVec2_test_classes_adv(), 10);
    }


    // --- test_closures ---
    #[test]
    fn test_closure_var() {
        assert_eq!(createMultiplier_test_closures(3), 15);
    }

    #[test]
    fn test_adder() {
        assert_eq!(makeAdder_test_closures(10), 15);
    }

    #[test]
    fn test_nested() {
        assert_eq!(outer_test_closures(3), 12);
    }


    // --- test_control_flow ---
    #[test]
    fn test_sw1() {
        assert_eq!(switchMulti_test_control_flow(2), 20);
    }

    #[test]
    fn test_sw_def() {
        assert_eq!(switchMulti_test_control_flow(99), 0);
    }

    #[test]
    fn test_chain() {
        assert_eq!(chain_test_control_flow(1, 2, 3), 6);
    }

    #[test]
    fn test_clamp_low() {
        assert_eq!(clamp_test_control_flow(-5, 0, 100), 0);
    }

    #[test]
    fn test_clamp_mid() {
        assert_eq!(clamp_test_control_flow(50, 0, 100), 50);
    }

    #[test]
    fn test_clamp_hi() {
        assert_eq!(clamp_test_control_flow(200, 0, 100), 100);
    }

    #[test]
    fn test_sign_pos_control_flow() {
        assert_eq!(sign_test_control_flow(42), 1);
    }

    #[test]
    fn test_sign_neg_control_flow() {
        assert_eq!(sign_test_control_flow(-7), -1);
    }

    #[test]
    fn test_sign_zero_control_flow() {
        assert_eq!(sign_test_control_flow(0), 0);
    }

    #[test]
    fn test_abs_pos() {
        assert_eq!(abs_test_control_flow(5), 5);
    }

    #[test]
    fn test_abs_neg() {
        assert_eq!(abs_test_control_flow(-5), 5);
    }

    #[test]
    fn test_min() {
        assert_eq!(min_test_control_flow(3, 7), 3);
    }

    #[test]
    fn test_max() {
        assert_eq!(max_test_control_flow(3, 7), 7);
    }


    // --- test_expressions ---
    #[test]
    fn test_hex() {
        assert_eq!(hexNum_test_expressions(), 255);
    }

    #[test]
    fn test_neg() {
        assert_eq!(negNum_test_expressions(), -42);
    }

    #[test]
    fn test_obj() {
        assert_eq!(makeObj_test_expressions(), 3);
    }

    #[test]
    fn test_arr_lit() {
        assert_eq!(arrayLiteral_test_expressions(), 20);
    }

    #[test]
    fn test_paren() {
        assert_eq!(parenExpr_test_expressions(3, 4), 14);
    }

    #[test]
    fn test_eq_true() {
        assert_eq!(strictEq_test_expressions(5, 5), true);
    }

    #[test]
    fn test_eq_false() {
        assert_eq!(strictEq_test_expressions(5, 3), false);
    }

    #[test]
    fn test_neq() {
        assert_eq!(strictNeq_test_expressions(5, 3), true);
    }

    #[test]
    fn test_lt() {
        assert_eq!(lt_test_expressions(3, 5), true);
    }

    #[test]
    fn test_le() {
        assert_eq!(le_test_expressions(5, 5), true);
    }

    #[test]
    fn test_gt() {
        assert_eq!(gt_test_expressions(5, 3), true);
    }

    #[test]
    fn test_ge() {
        assert_eq!(ge_test_expressions(3, 5), false);
    }

    #[test]
    fn test_ternary_pos() {
        assert_eq!(ternary_test_expressions(5), 1);
    }

    #[test]
    fn test_ternary_neg() {
        assert_eq!(ternary_test_expressions(-3), -1);
    }

    #[test]
    fn test_uneg() {
        assert_eq!(unaryNeg_test_expressions(5), -5);
    }

    #[test]
    fn test_fn_basic() {
        assert_eq!(simpleAdd_test_expressions(10, 20), 30);
    }

    #[test]
    fn test_multi_decl() {
        assert_eq!(multiDecl_test_expressions(), 6);
    }


    // --- test_template ---

    // --- test_types ---
    #[test]
    fn test_int_lit() {
        assert_eq!(intLiteral_test_types(), 42);
    }

    #[test]
    fn test_float_lit() {
        assert!((floatLiteral_test_types() - 3.14f64).abs() < 1e-10, "float_lit: got {}, expected 3.14", floatLiteral_test_types());
    }

    #[test]
    fn test_bool_lit() {
        assert_eq!(boolLiteral_test_types(), true);
    }

    #[test]
    fn test_add_ints() {
        assert_eq!(addInts_test_types(3, 5), 8);
    }

    #[test]
    fn test_compare() {
        assert_eq!(compare_test_types(5, 3), true);
    }

    #[test]
    fn test_multi_ret() {
        assert_eq!(multiReturn_test_types(5), 1);
    }

    #[test]
    fn test_default() {
        assert_eq!(withDefault_test_types(5, 10), 15);
    }

}
