// js2rust-bridge: Rust FFI bindings for translated JS/Zig code.
//
// This crate provides safe Rust wrappers for the C ABI functions
// exported by the Zig static libraries generated by js2rustc.
//
// Each `js2rust_bridge::js2rust_bridge!("out/{group}/cabi_exports.json")`
// invocation generates FFI bindings for one JS file group.

use js2rust_bridge_macro::js2rust_bridge;

pub mod host;

// === Auto-generated FFI bindings for each group ===
// Each macro invocation reads the cabi_exports.json at compile time
// and generates `unsafe extern "C"` + safe wrappers.

// Main group (core exports: add, multiply, greet, subtract, multiplyThree, divide)
js2rust_bridge!("out/main/cabi_exports.json");

// Builtins group (js_runtime helpers: mathRound, mathSign)
js2rust_bridge!("out/builtins/cabi_exports.json");

// Classes group (class wrappers: makePoint)
js2rust_bridge!("out/classes/cabi_exports.json");

// === String conversion helpers (kept for manual FFI if needed) ===

/// Convert a null-terminated C string pointer to a Rust &str.
///
/// # Safety
/// The pointer must be a valid, null-terminated C string allocated by Zig.
/// The returned &str borrows the memory; call the corresponding `free_*`
/// function after use to release the memory.
pub unsafe fn cstr_to_str<'a>(ptr: *const std::ffi::c_char) -> Option<&'a str> {
    if ptr.is_null() {
        return None;
    }
    let c_str = unsafe { std::ffi::CStr::from_ptr(ptr) };
    c_str.to_str().ok()
}

// === Tests ===
// Safe wrappers are generated by the macro, so we can test them directly.

#[cfg(test)]
mod tests {
    use super::*;

    // ── main group ──

    #[test]
    fn test_add() {
        assert_eq!(add_main(1, 2), 3);
        assert_eq!(add_main(0, 0), 0);
        assert_eq!(add_main(-5, 10), 5);
    }

    #[test]
    fn test_multiply() {
        assert_eq!(multiply_main(3, 4), 12);
        assert_eq!(multiply_main(0, 100), 0);
    }

    #[test]
    fn test_greet() {
        let result = greet_main("Rust");
        assert!(result.contains("Rust"));
    }

    #[test]
    fn test_subtract() {
        assert_eq!(subtract_main(10, 3), 7);
        assert_eq!(subtract_main(0, 5), -5);
    }

    #[test]
    fn test_multiply_three() {
        assert_eq!(multiplyThree_main(2, 3, 4), 24);
        assert_eq!(multiplyThree_main(1, 0, 5), 0);
    }

    #[test]
    fn test_divide() {
        assert_eq!(divide_main(10.0, 2.0), 5.0);
        assert!((divide_main(1.0, 3.0) - 0.3333333333333333).abs() < 1e-10);
    }

    // ── builtins group ──

    #[test]
    #[allow(clippy::approx_constant)]
    fn test_math_round() {
        assert_eq!(mathRound_builtins(3.14), 3.0);
        assert_eq!(mathRound_builtins(-2.7), -3.0);
        assert_eq!(mathRound_builtins(0.5), 1.0);
    }

    #[test]
    fn test_math_sign() {
        assert_eq!(mathSign_builtins(5), 1);
        assert_eq!(mathSign_builtins(-3), -1);
        assert_eq!(mathSign_builtins(0), 0);
    }

    // ── classes group ──

    #[test]
    fn test_make_point() {
        let p = makePoint_classes(3, 7);
        // makePoint returns i64 (fingerprint-encoded pointer to JsObject)
        // In a real scenario we'd call methods on the object.
        // For now, just verify the call doesn't panic.
        assert_ne!(p, 0); // non-null pointer
    }

    // ── host functions ──

    #[test]
    fn test_host_add() {
        assert_eq!(host::hostAdd(10, 20), 30);
    }

    #[test]
    fn test_host_multiply() {
        assert_eq!(host::hostMultiply(6, 7), 42);
    }

    #[test]
    fn test_host_fetch_user() {
        let name = std::ffi::CString::new("Alice").unwrap();
        let result = unsafe { host::hostFetchUser(name.as_ptr()) };
        assert_eq!(result.id, 5);
        let name_bytes: Vec<u8> = result
            .name_buf
            .iter()
            .take_while(|&&b| b != 0)
            .copied()
            .collect();
        let greeting = String::from_utf8(name_bytes).unwrap();
        assert_eq!(greeting, "Hello, Alice!");
    }
}
