// test262 source: language/expressions/addition/coerce-bigint-to-string.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_coerce_bigint_to_string() {
    // Copyright (C) 2017 Robin Templeton. All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    assert.sameValue(-1n + "", "-1");
    assert.sameValue("" + -1n, "-1");
    assert.sameValue(0n + "", "0");
    assert.sameValue("" + 0n, "0");
    assert.sameValue(1n + "", "1");
    assert.sameValue("" + 1n, "1");
    assert.sameValue(123456789000000000000000n + "", "123456789000000000000000");
    assert.sameValue("" + 123456789000000000000000n, "123456789000000000000000");
    assert.sameValue(-123456789000000000000000n + "", "-123456789000000000000000");
    assert.sameValue("" + -123456789000000000000000n, "-123456789000000000000000");
}
