// test262 source: test/language/expressions/addition/S11.6.1_A4_T2.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_addition_S11_6_1_A4_T2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (isNaN(Number.POSITIVE_INFINITY + Number.NEGATIVE_INFINITY) !== true ) {
      host_assert_fail('#1: Infinity + -Infinity === Not-a-Number. Actual: ' + (Infinity + -Infinity));
    }
    
    //CHECK#2
    if (isNaN(Number.NEGATIVE_INFINITY + Number.POSITIVE_INFINITY) !== true ) {
      host_assert_fail('#2: -Infinity + Infinity === Not-a-Number. Actual: ' + (-Infinity + Infinity));
    }
}
