// test262 source: language/expressions/addition/S11.6.1_A2.4_T4.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A2_4_T4() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if ((y = 1) + y !== 2) {
      throw new Test262Error('#1: (y = 1) + y === 2. Actual: ' + ((y = 1) + y));
    }
}
