// test262 source: test/language/statements/if/S12.5_A1.1_T2.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_statements_if_S12_5_A1_1_T2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    var c=0;
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#1
    if(0)
    	host_assert_fail('#1.1: 0 in expression is evaluated to false ');
    else
      c++;
    if (c!=1) host_assert_fail('#1.2: else branch don`t execute');
    //
    //////////////////////////////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#2
    if(false)
        host_assert_fail('#2.1: false in expression is evaluated to false ');
    else
      c++;
    if (c!=2) host_assert_fail('#2.2: else branch don`t execute');
    //
    //////////////////////////////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#3
    if(null)
    	host_assert_fail('#3.1: null in expression is evaluated to false ');
    else
      c++;
    if (c!=3) host_assert_fail('#3.2: else branch don`t execute');
    //
    //////////////////////////////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#4
    if(undefined)
    	host_assert_fail('#4.1: undefined in expression is evaluated to false ');
    else
      c++;
    if (c!=4) host_assert_fail('#4.2: else branch don`t execute');
    //
    //////////////////////////////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#5
    if("")
        host_assert_fail('#5.1: empty string in expression is evaluated to false ');
    else
      c++;
    if (c!=5) host_assert_fail('#5.2: else branch don`t execute');
    //
    //////////////////////////////////////////////////////////////////////////////
    
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#6
    if(NaN)
        host_assert_fail('#6.1: NaN in expression is evaluated to false ');
    else
      c++;
    if (c!=6) host_assert_fail('#6.2: else branch don`t execute');
    //
    //////////////////////////////////////////////////////////////////////////////
}
