// test262 source: test/language/statements/if/S12.5_A10_T2.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_statements_if_S12_5_A10_T2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#
    if(function __func(){return 0;}()){
        host_assert_fail('#1: Function expession inside the if expression is allowed');
    }else {
        ;
    }
    //
    //////////////////////////////////////////////////////////////////////////////
}
