// test262 source: test/language/expressions/strict-equals/S11.9.4_A3.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_strict_equals_S11_9_4_A3() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (!(true === true)) {
      host_assert_fail('#1: true === true');
    }
    
    //CHECK#2
    if (!(false === false)) {
      host_assert_fail('#2: false === false');
    }
    
    //CHECK#3
    if (true === false) {
      host_assert_fail('#3: true !== false');
    }
    
    //CHECK#4
    if (false === true) {
      host_assert_fail('#4: false !== true');
    }
}
