// test262 source: language/expressions/addition/coerce-symbol-to-prim-return-obj.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_coerce_symbol_to_prim_return_obj() {
    // Copyright (C) 2016 the V8 project authors. All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.


    var y = {};
    var retVal;

    y[Symbol.toPrimitive] = function() {
      return retVal;
    };

    retVal = {};
    assert.throws(TypeError, function() {
      0 + y;
    }, 'ordinary object value, right-hand side');
    assert.throws(TypeError, function() {
      y + 0;
    }, 'ordinary object value, left-hand side');

    retVal = (function() { return arguments; }());
    assert.throws(TypeError, function() {
      0 + y;
    }, 'arguments exotic object value, right-hand side');
    assert.throws(TypeError, function() {
      y + 0;
    }, 'arguments exotic object value, left-hand side');
}
