// test262 source: language/expressions/addition/get-symbol-to-prim-err.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_get_symbol_to_prim_err() {
    // Copyright (C) 2016 the V8 project authors. All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.


    var thrower = {};
    var counter = {};
    var callCount = 0;

    Object.defineProperty(thrower, Symbol.toPrimitive, {
      get: function() {
        throw new Test262Error();
      }
    });
    Object.defineProperty(counter, Symbol.toPrimitive, {
      get: function() {
        callCount += 1;
      }
    });

    assert.throws(Test262Error, function() {
      thrower + counter;
    }, 'error from property access of left-hand side');

    assert.sameValue(callCount, 0);

    assert.throws(Test262Error, function() {
      counter + thrower;
    }, 'error from property access of right-hand side');

    assert.sameValue(callCount, 1);
}
