// test262 source: test/language/expressions/division/S11.5.2_A4_T5.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_division_S11_5_2_A4_T5() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (Number.NEGATIVE_INFINITY / 1 !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#1: -Infinity / 1 === -Infinity. Actual: ' + (-Infinity / 1));
    }
    
    //CHECK#2
    if (Number.NEGATIVE_INFINITY / -1 !== Number.POSITIVE_INFINITY) {
      host_assert_fail('#2: -Infinity / -1 === Infinity. Actual: ' + (-Infinity / -1));
    }
    
    //CHECK#3
    if (Number.POSITIVE_INFINITY / 1 !== Number.POSITIVE_INFINITY) {
      host_assert_fail('#3: Infinity / 1 === Infinity. Actual: ' + (Infinity / 1));
    }
    
    //CHECK#4
    if (Number.POSITIVE_INFINITY / -1 !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#4: Infinity / -1 === -Infinity. Actual: ' + (Infinity / -1));
    }
    
    //CHECK#5
    if (Number.POSITIVE_INFINITY / -Number.MAX_VALUE !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#5: Infinity / -Number.MAX_VALUE === -Infinity. Actual: ' + (Infinity / -Number.MAX_VALUE));
    }
    
    //CHECK#6
    if (Number.NEGATIVE_INFINITY / Number.MIN_VALUE !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#6: -Infinity / Number.MIN_VALUE === -Infinity. Actual: ' + (-Infinity / Number.MIN_VALUE));
    }
}
