// test262 source: language/expressions/addition/S11.6.1_A3.2_T2.2.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_2_T2_2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if (true + "1" !== "true1") {
      throw new Test262Error('#1: true + "1" === "true1". Actual: ' + (true + "1"));
    }

    //CHECK#2
    if ("1" + true !== "1true") {
      throw new Test262Error('#2: "1" + true === "1true". Actual: ' + ("1" + true));
    }

    //CHECK#3
    if (new Boolean(true) + "1" !== "true1") {
      throw new Test262Error('#3: new Boolean(true) + "1" === "true1". Actual: ' + (new Boolean(true) + "1"));
    }

    //CHECK#4
    if ("1" + new Boolean(true) !== "1true") {
      throw new Test262Error('#4: "1" + new Boolean(true) === "1true". Actual: ' + ("1" + new Boolean(true)));
    }

    //CHECK#5
    if (true + new String("1") !== "true1") {
      throw new Test262Error('#5: true + new String("1") === "true1". Actual: ' + (true + new String("1")));
    }

    //CHECK#6
    if (new String("1") + true !== "1true") {
      throw new Test262Error('#6: new String("1") + true === "1true". Actual: ' + (new String("1") + true));
    }

    //CHECK#7
    if (new Boolean(true) + new String("1") !== "true1") {
      throw new Test262Error('#7: new Boolean(true) + new String("1") === "true1". Actual: ' + (new Boolean(true) + new String("1")));
    }

    //CHECK#8
    if (new String("1") + new Boolean(true) !== "1true") {
      throw new Test262Error('#8: new String("1") + new Boolean(true) === "1true". Actual: ' + (new String("1") + new Boolean(true)));
    }
}
