// test262 source: language/expressions/addition/bigint-errors.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_bigint_errors() {
    // Copyright (C) 2017 Josh Wolfe. All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.

    assert.throws(TypeError, function() {
      Symbol('1') + 0n;
    }, 'Symbol("1") + 0n throws TypeError');

    assert.throws(TypeError, function() {
      0n + Symbol('1');
    }, '0n + Symbol("1") throws TypeError');

    assert.throws(TypeError, function() {
      Object(Symbol('1')) + 0n;
    }, 'Object(Symbol("1")) + 0n throws TypeError');

    assert.throws(TypeError, function() {
      0n + Object(Symbol('1'));
    }, '0n + Object(Symbol("1")) throws TypeError');

    assert.throws(TypeError, function() {
      ({
        [Symbol.toPrimitive]: function() {
          return Symbol('1');
        }
      }) + 0n;
    }, '({[Symbol.toPrimitive]: function() {return Symbol("1");}}) + 0n throws TypeError');

    assert.throws(TypeError, function() {
      0n + {
        [Symbol.toPrimitive]: function() {
          return Symbol('1');
        }
      };
    }, '0n + {[Symbol.toPrimitive]: function() {return Symbol("1");}} throws TypeError');

    assert.throws(TypeError, function() {
      ({
        valueOf: function() {
          return Symbol('1');
        }
      }) + 0n;
    }, '({valueOf: function() {return Symbol("1");}}) + 0n throws TypeError');

    assert.throws(TypeError, function() {
      0n + {
        valueOf: function() {
          return Symbol('1');
        }
      };
    }, '0n + {valueOf: function() {return Symbol("1");}} throws TypeError');

    assert.throws(TypeError, function() {
      ({
        toString: function() {
          return Symbol('1');
        }
      }) + 0n;
    }, '({toString: function() {return Symbol("1");}}) + 0n throws TypeError');

    assert.throws(TypeError, function() {
      0n + {
        toString: function() {
          return Symbol('1');
        }
      };
    }, '0n + {toString: function() {return Symbol("1");}} throws TypeError');
}
