// test262 source: language/expressions/addition/S11.6.1_A3.2_T2.4.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_2_T2_4() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if ("1" + null !== "1null") {
      throw new Test262Error('#1: "1" + null === "1null". Actual: ' + ("1" + null));
    }

    //CHECK#2
    if (null + "1" !== "null1") {
      throw new Test262Error('#2: null + "1" === "null1". Actual: ' + (null + "1"));
    }

    //CHECK#3
    if (new String("1") + null !== "1null") {
      throw new Test262Error('#3: new String("1") + null === "1null". Actual: ' + (new String("1") + null));
    }

    //CHECK#4
    if (null + new String("1") !== "null1") {
      throw new Test262Error('#4: null + new String("1") === "null1". Actual: ' + (null + new String("1")));
    }
}
