// test262 source: language/expressions/addition/coerce-symbol-to-prim-err.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_coerce_symbol_to_prim_err() {
    // Copyright (C) 2016 the V8 project authors. All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.


    var thrower = {};
    var counter = {};
    var log;

    Object.defineProperty(thrower, Symbol.toPrimitive, {
      get: function() {
        log += 'accessThrower';
        return function() { throw new Test262Error(); };
      }
    });
    Object.defineProperty(counter, Symbol.toPrimitive, {
      get: function() {
        log += 'accessCounter';
        return function() { log += 'callCounter'; };
      }
    });

    log = '';

    assert.throws(Test262Error, function() {
      thrower + counter;
    }, 'error thrown by left-hand side');
    assert.sameValue(log, 'accessThrower');

    log = '';

    assert.throws(Test262Error, function() {
      counter + thrower;
    }, 'error thrown by right-hand side');
    assert.sameValue(log, 'accessCountercallCounteraccessThrower');
}
