// test262 source: language/expressions/addition/S11.6.1_A2.4_T2.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A2_4_T2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    var x = function () { throw "x"; };
    var y = function () { throw "y"; };
    try {
       x() + y();
       throw new Test262Error('#1.1: var x = function () { throw "x"; }; var y = function () { throw "y"; }; x() + y() throw "x". Actual: ' + (x() + y()));
    } catch (e) {
       if (e === "y") {
         throw new Test262Error('#1.2: First expression is evaluated first, and then second expression');
       } else {
         if (e !== "x") {
           throw new Test262Error('#1.3: var x = function () { throw "x"; }; var y = function () { throw "y"; }; x() + y() throw "x". Actual: ' + (e));
         }
       }
    }
}
