// test262 source: test/language/expressions/division/S11.5.2_A4_T1.1.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_division_S11_5_2_A4_T1_1() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (isNaN(Number.NaN / Number.NaN) !== true) {
      host_assert_fail('#1: NaN / NaN === Not-a-Number. Actual: ' + (NaN / NaN));
    }  
    
    //CHECK#2
    if (isNaN(Number.NaN / +0) !== true) {
      host_assert_fail('#2: NaN / +0 === Not-a-Number. Actual: ' + (NaN / +0)); 
    } 
    
    //CHECK#3
    if (isNaN(Number.NaN / -0) !== true) {
      host_assert_fail('#3: NaN / -0 === Not-a-Number. Actual: ' + (NaN / -0)); 
    } 
    
    //CHECK#4
    if (isNaN(Number.NaN / Number.POSITIVE_INFINITY) !== true) {
      host_assert_fail('#4: NaN / Infinity === Not-a-Number. Actual: ' + (NaN / Infinity));
    } 
    
    //CHECK#5
    if (isNaN(Number.NaN / Number.NEGATIVE_INFINITY) !== true) {
      host_assert_fail('#5: NaN / -Infinity === Not-a-Number. Actual: ' + (NaN / -Infinity)); 
    } 
    
    //CHECK#6
    if (isNaN(Number.NaN / Number.MAX_VALUE) !== true) {
      host_assert_fail('#6: NaN / Number.MAX_VALUE === Not-a-Number. Actual: ' + (NaN / Number.MAX_VALUE));
    } 
    
    //CHECK#7
    if (isNaN(Number.NaN / Number.MIN_VALUE) !== true) {
      host_assert_fail('#7: NaN / Number.MIN_VALUE === Not-a-Number. Actual: ' + (NaN / Number.MIN_VALUE)); 
    }
    
    //CHECK#8
    if (isNaN(Number.NaN / 1) !== true) {
      host_assert_fail('#8: NaN / 1 === Not-a-Number. Actual: ' + (NaN / 1));  
    }
}
