// test262 source: language/expressions/addition/symbol-to-string.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_symbol_to_string() {
    // Copyright (C) 2013 the V8 project authors. All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.


    var s = Symbol('66');
    assert.throws(TypeError, function() {
      s + '';
    });
}
