// test262 source: test/language/expressions/multiplication/S11.5.1_A4_T3.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_multiplication_S11_5_1_A4_T3() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (isNaN(Number.NEGATIVE_INFINITY * 0) !== true) {
      host_assert_fail('#1: Infinity * 0 === Not-a-Number. Actual: ' + (Infinity * 0));
    }
    
    //CHECK#2
    if (isNaN(-0 * Number.NEGATIVE_INFINITY) !== true) {
      host_assert_fail('#2: -0 * -Infinity === Not-a-Number. Actual: ' + (-0 * -Infinity));
    }
    
    //CHECK#3
    if (isNaN(Number.POSITIVE_INFINITY * -0) !== true) {
      host_assert_fail('#3: Infinity * -0 === Not-a-Number. Actual: ' + (Infinity * -0));
    }
    
    //CHECK#4
    if (isNaN(0 * Number.POSITIVE_INFINITY) !== true) {
      host_assert_fail('#4: 0 * Infinity === Not-a-Number. Actual: ' + (0 * Infinity));
    }
    
    //CHECK#5
    if (isNaN(Number.NEGATIVE_INFINITY * -0) !== true) {
      host_assert_fail('#5: Infinity * -0 === Not-a-Number. Actual: ' + (Infinity * -0));
    }
    
    //CHECK#6
    if (isNaN(0 * Number.NEGATIVE_INFINITY) !== true) {
      host_assert_fail('#6: 0 * -Infinity === Not-a-Number. Actual: ' + (0 * -Infinity));
    }
    
    //CHECK#7
    if (isNaN(Number.POSITIVE_INFINITY * 0) !== true) {
      host_assert_fail('#7: Infinity * 0 === Not-a-Number. Actual: ' + (Infinity * 0));
    }
    
    //CHECK#8
    if (isNaN(-0 * Number.POSITIVE_INFINITY) !== true) {
      host_assert_fail('#8: -0 * Infinity === Not-a-Number. Actual: ' + (-0 * Infinity));
    }
}
