// test262 source: test/language/expressions/addition/S11.6.1_A4_T8.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_addition_S11_6_1_A4_T8() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (Number.MAX_VALUE + Number.MAX_VALUE !== Number.POSITIVE_INFINITY) {
      host_assert_fail('#1: Number.MAX_VALUE + Number.MAX_VALUE === Number.POSITIVE_INFINITY. Actual: ' + (Number.MAX_VALUE + Number.MAX_VALUE));
    }
    
    //CHECK#2
    if (-Number.MAX_VALUE - Number.MAX_VALUE !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#2: -Number.MAX_VALUE - Number.MAX_VALUE === Number.NEGATIVE_INFINITY. Actual: ' + (-Number.MAX_VALUE - Number.MAX_VALUE));
    }
    
    //CHECK#3
    if (1e+308 + 1e+308 !== Number.POSITIVE_INFINITY) {
      host_assert_fail('#3: 1e+308 + 1e+308 === Number.POSITIVE_INFINITY. Actual: ' + (1e+308 + 1e+308));
    }
    
    //CHECK#4
    if (-8.99e+307 - 8.99e+307 !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#4: -8.99e+307 - 8.99e+307 === Number.NEGATIVE_INFINITY. Actual: ' + (-8.99e+307 - 8.99e+307));
    }
}
