// test262 source: test/language/expressions/multiplication/S11.5.1_A4_T7.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_multiplication_S11_5_1_A4_T7() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (Number.MIN_VALUE * 0.1 !== 0) {
      host_assert_fail('#1: Number.MIN_VALUE * 0.1 === 0. Actual: ' + (Number.MIN_VALUE * 0.1));
    }
    
    //CHECK#2
    if (-0.1 * Number.MIN_VALUE !== -0) {
      host_assert_fail('#2.1: -0.1 * Number.MIN_VALUE === -0. Actual: ' + (-0.1 * Number.MIN_VALUE));
    } else {
      if (1 / (-0.1 * Number.MIN_VALUE) !== Number.NEGATIVE_INFINITY) {
        host_assert_fail('#2.2: -0.1 * Number.MIN_VALUE === -0. Actual: +0');
      }
    }
    
    //CHECK#3
    if (Number.MIN_VALUE * 0.5 !== 0) {
      host_assert_fail('#3: Number.MIN_VALUE * 0.5 === 0. Actual: ' + (Number.MIN_VALUE * 0.5));
    }
    
    //CHECK#4
    if (-0.5 * Number.MIN_VALUE !== -0) {
      host_assert_fail('#4.1: -0.5 * Number.MIN_VALUE === -0. Actual: ' + (-0.5 * Number.MIN_VALUE));
    } else {
      if (1 / (-0.5 * Number.MIN_VALUE) !== Number.NEGATIVE_INFINITY) {
        host_assert_fail('#4.2: -0.5 * Number.MIN_VALUE === -0. Actual: +0');
      }
    }
    
    //CHECK#5
    if (Number.MIN_VALUE * 0.51 !== Number.MIN_VALUE) {
      host_assert_fail('#5: Number.MIN_VALUE * 0.51 === Number.MIN_VALUE. Actual: ' + (Number.MIN_VALUE * 0.51));
    }
    
    //CHECK#6
    if (-0.51 * Number.MIN_VALUE !== -Number.MIN_VALUE) {
      host_assert_fail('#6: -0.51 * Number.MIN_VALUE === -Number.MIN_VALUE. Actual: ' + (-0.51 * Number.MIN_VALUE));
    }
    
    //CHECK#7
    if (Number.MIN_VALUE * 0.9 !== Number.MIN_VALUE) {
      host_assert_fail('#7: Number.MIN_VALUE * 0.9 === Number.MIN_VALUE. Actual: ' + (Number.MIN_VALUE * 0.9));
    }
    
    //CHECK#8
    if (-0.9 * Number.MIN_VALUE !== -Number.MIN_VALUE) {
      host_assert_fail('#8: -0.9 * Number.MIN_VALUE === -Number.MIN_VALUE. Actual: ' + (-0.9 * Number.MIN_VALUE));
    }
}
