// test262 source: language/expressions/addition/S11.6.1_A3.1_T2.5.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_1_T2_5() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if (true + null !== 1) {
      throw new Test262Error('#1: true + null === 1. Actual: ' + (true + null));
    }

    //CHECK#2
    if (null + true !== 1) {
      throw new Test262Error('#2: null + true === 1. Actual: ' + (null + true));
    }

    //CHECK#3
    if (new Boolean(true) + null !== 1) {
      throw new Test262Error('#3: new Boolean(true) + null === 1. Actual: ' + (new Boolean(true) + null));
    }

    //CHECK#4
    if (null + new Boolean(true) !== 1) {
      throw new Test262Error('#4: null + new Boolean(true) === 1. Actual: ' + (null + new Boolean(true)));
    }
}
