// test262 source: test/language/expressions/strict-equals/S11.9.4_A4.3.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_strict_equals_S11_9_4_A4_3() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (!(Number.POSITIVE_INFINITY === Number.POSITIVE_INFINITY)) {
      host_assert_fail('#1: +Infinity === +Infinity');
    }
    
    //CHECK#2
    if (!(Number.NEGATIVE_INFINITY === Number.NEGATIVE_INFINITY)) {
      host_assert_fail('#2: -Infinity === -Infinity');
    }
    
    //CHECK#3
    if (!(13 === 13)) {
      host_assert_fail('#3: 13 === 13');
    }
    
    //CHECK#4
    if (!(-13 === -13)) {
      host_assert_fail('#4: -13 === -13');
    }
    
    //CHECK#5
    if (!(1.3 === 1.3)) {
      host_assert_fail('#5: 1.3 === 1.3');
    }
    
    //CHECK#6
    if (!(-1.3 === -1.3)) {
      host_assert_fail('#6: -1.3 === -1.3');
    }
    
    //CHECK#7
    if (!(Number.POSITIVE_INFINITY === -Number.NEGATIVE_INFINITY)) {
      host_assert_fail('#7: +Infinity === -(-Infinity)');
    }
    
    //CHECK#8
    if (1 === 0.999999999999) {
      host_assert_fail('#8: 1 !== 0.999999999999');
    }
    
    //CHECK#9
    if (!(1.0 === 1)) {
      host_assert_fail('#9: 1.0 === 1');
    }
}
