// test262 source: language/expressions/addition/coerce-symbol-to-prim-invocation.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_coerce_symbol_to_prim_invocation() {
    // Copyright (C) 2016 the V8 project authors. All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.


    var left = {};
    var right = {};
    var log = '';
    var leftThisVal, rightThisVal, leftArgs, rightArgs;

    left[Symbol.toPrimitive] = function() {
      log += 'left';
      leftThisVal = this;
      leftArgs = arguments;
    };

    right[Symbol.toPrimitive] = function() {
      log += 'right';
      rightThisVal = this;
      rightArgs = arguments;
    };


    left + right;

    assert.sameValue(log, 'leftright', 'methods invoked in correct sequence');

    assert.sameValue(leftThisVal, left, 'left-hand side `this` value');
    assert.sameValue(leftArgs.length, 1, 'left-hand side argument length');
    assert.sameValue(leftArgs[0], 'default', 'left-hand side argument value');

    assert.sameValue(rightThisVal, right, 'right-hand side `this` value');
    assert.sameValue(rightArgs.length, 1, 'right-hand side argument length');
    assert.sameValue(rightArgs[0], 'default', 'right-hand side argument value');
}
