// test262 source: language/expressions/addition/S11.6.1_A3.2_T1.2.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_2_T1_2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if (({} + function(){return 1}) !== ({}.toString() + function(){return 1}.toString())) {
      throw new Test262Error('#1: ({} + function(){return 1}) === ({}.toString() + function(){return 1}.toString()). Actual: ' + (({} + function(){return 1})));
    }

    //CHECK#2
    if ((function(){return 1} + {}) !== (function(){return 1}.toString() + {}.toString())) {
      throw new Test262Error('#2: (function(){return 1} + {}) === (function(){return 1}.toString() + {}.toString()). Actual: ' + ((function(){return 1} + {})));
    }

    //CHECK#3
    if ((function(){return 1} + function(){return 1}) !== (function(){return 1}.toString() + function(){return 1}.toString())) {
      throw new Test262Error('#3: (function(){return 1} + function(){return 1}) === (function(){return 1}.toString() + function(){return 1}.toString()). Actual: ' + ((function(){return 1} + function(){return 1})));
    }

    //CHECK#4
    if (({} + {}) !== ({}.toString() + {}.toString())) {
      throw new Test262Error('#4: ({} + {}) === ({}.toString() + {}.toString()). Actual: ' + (({} + {})));
    }
}
