// test262 source: test/language/expressions/multiplication/S11.5.1_A4_T4.js
// AUTO-GENERATED by scan_test262.py

// --- assert helpers (non-exported → Zig anytype) ---
function assert_same_value(actual, expected, message) {
    if (actual !== expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.sameValue failed"); }
    }
}
function assert_not_same_value(actual, expected, message) {
    if (actual === expected) {
        if (message !== undefined) { host_assert_fail(message); }
        else { host_assert_fail("assert.notSameValue failed"); }
    }
}

export function test262_language_expressions_multiplication_S11_5_1_A4_T4() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.
    
    
    
    //CHECK#1
    if (Number.NEGATIVE_INFINITY * Number.NEGATIVE_INFINITY !== Number.POSITIVE_INFINITY) {
      host_assert_fail('#1: -Infinity * -Infinity === Infinity. Actual: ' + (-Infinity * -Infinity));
    }
    
    //CHECK#2
    if (Number.POSITIVE_INFINITY * Number.POSITIVE_INFINITY !== Number.POSITIVE_INFINITY) {
      host_assert_fail('#2: Infinity * Infinity === Infinity. Actual: ' + (Infinity * Infinity));
    }
    
    //CHECK#3
    if (Number.NEGATIVE_INFINITY * Number.POSITIVE_INFINITY !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#3: -Infinity * Infinity === -Infinity. Actual: ' + (-Infinity * Infinity));
    }
    
    //CHECK#4
    if (Number.POSITIVE_INFINITY * Number.NEGATIVE_INFINITY !== Number.NEGATIVE_INFINITY) {
      host_assert_fail('#4: Infinity * -Infinity === -Infinity. Actual: ' + (Infinity * -Infinity));
    }
}
