// test262 source: language/expressions/addition/S11.6.1_A3.1_T2.4.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_1_T2_4() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if (isNaN(true + undefined) !== true) {
      throw new Test262Error('#1: true + undefined === Not-a-Number. Actual: ' + (true + undefined));
    }

    //CHECK#2
    if (isNaN(undefined + true) !== true) {
      throw new Test262Error('#2: undefined + true === Not-a-Number. Actual: ' + (undefined + true));
    }

    //CHECK#3
    if (isNaN(new Boolean(true) + undefined) !== true) {
      throw new Test262Error('#3: new Boolean(true) + undefined === Not-a-Number. Actual: ' + (new Boolean(true) + undefined));
    }

    //CHECK#4
    if (isNaN(undefined + new Boolean(true)) !== true) {
      throw new Test262Error('#4: undefined + new Boolean(true) === Not-a-Number. Actual: ' + (undefined + new Boolean(true)));
    }
}
