// test262 source: language/expressions/addition/S11.6.1_A3.2_T2.3.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_2_T2_3() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if ("1" + undefined !== "1undefined") {
      throw new Test262Error('#1: "1" + undefined === "1undefined". Actual: ' + ("1" + undefined));
    }

    //CHECK#2
    if (undefined + "1" !== "undefined1") {
      throw new Test262Error('#2: undefined + "1" === "undefined1". Actual: ' + (undefined + "1"));
    }

    //CHECK#3
    if (new String("1") + undefined !== "1undefined") {
      throw new Test262Error('#3: new String("1") + undefined === "1undefined". Actual: ' + (new String("1") + undefined));
    }

    //CHECK#4
    if (undefined + new String("1") !== "undefined1") {
      throw new Test262Error('#4: undefined + new String("1") === "undefined1". Actual: ' + (undefined + new String("1")));
    }
}
