// test262 source: language/expressions/addition/S11.6.1_A3.1_T1.2.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_1_T1_2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if (1 + 1 !== 2) {
      throw new Test262Error('#1: 1 + 1 === 2. Actual: ' + (1 + 1));
    }

    //CHECK#2
    if (new Number(1) + 1 !== 2) {
      throw new Test262Error('#2: new Number(1) + 1 === 2. Actual: ' + (new Number(1) + 1));
    }

    //CHECK#3
    if (1 + new Number(1) !== 2) {
      throw new Test262Error('#3: 1 + new Number(1) === 2. Actual: ' + (1 + new Number(1)));
    }

    //CHECK#4
    if (new Number(1) + new Number(1) !== 2) {
      throw new Test262Error('#4: new Number(1) + new Number(1) === 2. Actual: ' + (new Number(1) + new Number(1)));
    }
}
