// test262 source: language/expressions/addition/S11.6.1_A3.1_T1.1.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_1_T1_1() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if (true + true !== 2) {
      throw new Test262Error('#1: true + true === 2. Actual: ' + (true + true));
    }

    //CHECK#2
    if (new Boolean(true) + true !== 2) {
      throw new Test262Error('#2: new Boolean(true) + true === 2. Actual: ' + (new Boolean(true) + true));
    }

    //CHECK#3
    if (true + new Boolean(true) !== 2) {
      throw new Test262Error('#3: true + new Boolean(true) === 2. Actual: ' + (true + new Boolean(true)));
    }

    //CHECK#4
    if (new Boolean(true) + new Boolean(true) !== 2) {
      throw new Test262Error('#4: new Boolean(true) + new Boolean(true) === 2. Actual: ' + (new Boolean(true) + new Boolean(true)));
    }
}
