// test262 source: language/expressions/addition/S11.6.1_A3.1_T2.2.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A3_1_T2_2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    if (1 + null !== 1) {
      throw new Test262Error('#1: 1 + null === 1. Actual: ' + (1 + null));
    }

    //CHECK#2
    if (null + 1 !== 1) {
      throw new Test262Error('#2: null + 1 === 1. Actual: ' + (null + 1));
    }

    //CHECK#3
    if (new Number(1) + null !== 1) {
      throw new Test262Error('#3: new Number(1) + null === 1. Actual: ' + (new Number(1) + null));
    }

    //CHECK#4
    if (null + new Number(1) !== 1) {
      throw new Test262Error('#4: null + new Number(1) === 1. Actual: ' + (null + new Number(1)));
    }
}
