// test262 source: language/expressions/addition/S11.6.1_A2.4_T1.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A2_4_T1() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    var x = 0; 
    if ((x = 1) + x !== 2) {
      throw new Test262Error('#1: var x = 0; (x = 1) + x === 2. Actual: ' + ((x = 1) + x));
    }

    //CHECK#2
    var x = 0; 
    if (x + (x = 1) !== 1) {
      throw new Test262Error('#2: var x = 0; x + (x = 1) === 1. Actual: ' + (x + (x = 1)));
    }
}
