// test262 source: language/expressions/addition/S11.6.1_A2.2_T2.js
// AUTO-GENERATED by scan_test262.py

export function test262_language_expressions_addition_S11_6_1_A2_2_T2() {
    // Copyright 2009 the Sputnik authors.  All rights reserved.
    // This code is governed by the BSD license found in the LICENSE file.



    //CHECK#1
    var date = new Date(0);
    if (date + date !== date.toString() + date.toString()) {
      throw new Test262Error('#1: var date = new Date(0); date + date === date.toString() + date.toString(). Actual: ' + (date + date));  
    }

    //CHECK#2
    var date = new Date(0);
    if (date + 0 !== date.toString() + "0") {
      throw new Test262Error('#2: var date = new Date(0); date + 0 === date.toString() + "0". Actual: ' + (date + 0));  
    }

    //CHECK#3
    var date = new Date(0);
    if (date + true !== date.toString() + "true") {
      throw new Test262Error('#3: var date = new Date(0); date + true === date.toString() + "true". Actual: ' + (date + true));  
    }

    //CHECK#4
    var date = new Date(0);
    if (date + new Object() !== date.toString() + "[object Object]") {
      throw new Test262Error('#4: var date = new Date(0); date + new Object() === date.toString() + "[object Object]". Actual: ' + (date + new Object()));  
    }
}
