[project]
js_dir = "js_src"
js_files = [
    "app.js",
    "test262_language_expressions_addition_S11_6_1_A3_1_T1_3.js",
    "test262_language_expressions_addition_S11_6_1_A4_T1.js",
    "test262_language_expressions_addition_S11_6_1_A4_T2.js",
    "test262_language_expressions_addition_S11_6_1_A4_T3.js",
    "test262_language_expressions_addition_S11_6_1_A4_T4.js",
    "test262_language_expressions_addition_S11_6_1_A4_T5.js",
    "test262_language_expressions_addition_S11_6_1_A4_T6.js",
    "test262_language_expressions_addition_S11_6_1_A4_T7.js",
    "test262_language_expressions_addition_S11_6_1_A4_T8.js",
    "test262_language_expressions_addition_S11_6_1_A4_T9.js",
    "test262_language_expressions_multiplication_line_terminator.js",
    "test262_language_expressions_multiplication_S11_5_1_A3_T1_4.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T1_1.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T1_2.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T2.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T3.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T4.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T5.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T6.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T7.js",
    "test262_language_expressions_multiplication_S11_5_1_A4_T8.js",
    "test262_language_expressions_subtraction_S11_6_2_A3_T1_4.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T1.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T2.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T3.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T4.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T5.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T6.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T7.js",
    "test262_language_expressions_subtraction_S11_6_2_A4_T8.js",
    "test262_language_expressions_division_line_terminator.js",
    "test262_language_expressions_division_no_magic_asi.js",
    "test262_language_expressions_division_S11_5_2_A3_T1_4.js",
    "test262_language_expressions_division_S11_5_2_A4_T1_1.js",
    "test262_language_expressions_division_S11_5_2_A4_T1_2.js",
    "test262_language_expressions_division_S11_5_2_A4_T10.js",
    "test262_language_expressions_division_S11_5_2_A4_T2.js",
    "test262_language_expressions_division_S11_5_2_A4_T3.js",
    "test262_language_expressions_division_S11_5_2_A4_T4.js",
    "test262_language_expressions_division_S11_5_2_A4_T5.js",
    "test262_language_expressions_division_S11_5_2_A4_T6.js",
    "test262_language_expressions_division_S11_5_2_A4_T8.js",
    "test262_language_expressions_division_S11_5_2_A4_T9.js",
    "test262_language_statements_if_empty_statement.js",
    "test262_language_statements_if_S12_5_A1_1_T1.js",
    "test262_language_statements_if_S12_5_A1_1_T2.js",
    "test262_language_statements_if_S12_5_A10_T1.js",
    "test262_language_statements_if_S12_5_A10_T2.js",
    "test262_language_statements_if_S12_5_A12_T1.js",
    "test262_language_statements_if_S12_5_A12_T2.js",
    "test262_language_statements_if_S12_5_A12_T3.js",
    "test262_language_statements_if_S12_5_A12_T4.js",
    "test262_language_statements_if_S12_5_A1_T1.js",
    "test262_language_statements_if_S12_5_A1_T2.js",
    "test262_language_expressions_strict_equals_S11_9_4_A3.js",
    "test262_language_expressions_strict_equals_S11_9_4_A4_2.js",
    "test262_language_expressions_strict_equals_S11_9_4_A4_3.js",
    "test262_language_expressions_strict_equals_S11_9_4_A5.js",
    "test262_language_expressions_strict_equals_S11_9_4_A6_2.js",
]

[build]
force_rebuild = true

[[host_functions]]
name = "host_assert_fail"
params = ["str"]
returns = "void"
