// tests/integration_test.rs
// Integration tests for try-catch nesting verification

// Note: function names are {export_name}_main (generated by js2rust_bridge macro)
// Functions with can_throw: true return Result<i64, Error>

#[test]
fn test_nested_try_catch() {
    // Expected: 2 + 10 + 1000 = 1012
    let result = super::testNestedTryCatch_main().unwrap();
    assert_eq!(result, 1012, "testNestedTryCatch() should return 1012");
}

#[test]
fn test_nested_try_catch_with_throw() {
    // Expected: 2 + 10 + 100 + 1000 = 1112
    let result = super::testNestedTryCatchWithThrow_main().unwrap();
    assert_eq!(
        result, 1112,
        "testNestedTryCatchWithThrow() should return 1112"
    );
}

#[test]
fn test_try_catch_with_resource() {
    // Expected: 43 (x + 1 = 42 + 1)
    let result = super::testTryCatchWithResource_main().unwrap();
    assert_eq!(result, 43, "testTryCatchWithResource() should return 43");
}
