// src/main.rs - test262 conformance test runner (AUTO-GENERATED by scan_test262.py)
//
// Usage:
//   test262-project                    Run all test262 tests
//   test262-project --list             List all available tests
//   test262-project <test_name>        Run a single test (direct call mode)
//   test262-project --all              Same as default

use js2rust_bridge::js2rust_bridge;
use std::env;
use std::process::Command;

mod host;

js2rust_bridge!();

// Flush C stdio buffers (Zig runtime writes via C FFI, not Rust stdout).
extern "C" {
    fn fflush(stream: *mut std::ffi::c_void) -> i32;
}

fn flush_stdout() {
    unsafe {
        fflush(std::ptr::null_mut());
    }
}

/// All test262 test names, matching the export function names in js_src/*.js.
const ALL_TESTS: &[&str] = &[
    "test262_language_expressions_addition_S11_6_1_A3_1_T1_3",
    "test262_language_expressions_addition_S11_6_1_A4_T1",
    "test262_language_expressions_addition_S11_6_1_A4_T2",
    "test262_language_expressions_addition_S11_6_1_A4_T3",
    "test262_language_expressions_addition_S11_6_1_A4_T4",
    "test262_language_expressions_addition_S11_6_1_A4_T5",
    "test262_language_expressions_addition_S11_6_1_A4_T6",
    "test262_language_expressions_addition_S11_6_1_A4_T7",
    "test262_language_expressions_addition_S11_6_1_A4_T8",
    "test262_language_expressions_addition_S11_6_1_A4_T9",
    "test262_language_expressions_multiplication_line_terminator",
    "test262_language_expressions_multiplication_S11_5_1_A3_T1_4",
    "test262_language_expressions_multiplication_S11_5_1_A4_T1_1",
    "test262_language_expressions_multiplication_S11_5_1_A4_T1_2",
    "test262_language_expressions_multiplication_S11_5_1_A4_T2",
    "test262_language_expressions_multiplication_S11_5_1_A4_T3",
    "test262_language_expressions_multiplication_S11_5_1_A4_T4",
    "test262_language_expressions_multiplication_S11_5_1_A4_T5",
    "test262_language_expressions_multiplication_S11_5_1_A4_T6",
    "test262_language_expressions_multiplication_S11_5_1_A4_T7",
    "test262_language_expressions_multiplication_S11_5_1_A4_T8",
    "test262_language_expressions_subtraction_S11_6_2_A3_T1_4",
    "test262_language_expressions_subtraction_S11_6_2_A4_T1",
    "test262_language_expressions_subtraction_S11_6_2_A4_T2",
    "test262_language_expressions_subtraction_S11_6_2_A4_T3",
    "test262_language_expressions_subtraction_S11_6_2_A4_T4",
    "test262_language_expressions_subtraction_S11_6_2_A4_T5",
    "test262_language_expressions_subtraction_S11_6_2_A4_T6",
    "test262_language_expressions_subtraction_S11_6_2_A4_T7",
    "test262_language_expressions_subtraction_S11_6_2_A4_T8",
    "test262_language_expressions_division_line_terminator",
    "test262_language_expressions_division_no_magic_asi",
    "test262_language_expressions_division_S11_5_2_A3_T1_4",
    "test262_language_expressions_division_S11_5_2_A4_T1_1",
    "test262_language_expressions_division_S11_5_2_A4_T1_2",
    "test262_language_expressions_division_S11_5_2_A4_T10",
    "test262_language_expressions_division_S11_5_2_A4_T2",
    "test262_language_expressions_division_S11_5_2_A4_T3",
    "test262_language_expressions_division_S11_5_2_A4_T4",
    "test262_language_expressions_division_S11_5_2_A4_T5",
    "test262_language_expressions_division_S11_5_2_A4_T6",
    "test262_language_expressions_division_S11_5_2_A4_T8",
    "test262_language_expressions_division_S11_5_2_A4_T9",
    "test262_language_statements_if_empty_statement",
    "test262_language_statements_if_S12_5_A1_1_T1",
    "test262_language_statements_if_S12_5_A1_1_T2",
    "test262_language_statements_if_S12_5_A10_T1",
    "test262_language_statements_if_S12_5_A10_T2",
    "test262_language_statements_if_S12_5_A12_T1",
    "test262_language_statements_if_S12_5_A12_T2",
    "test262_language_statements_if_S12_5_A12_T3",
    "test262_language_statements_if_S12_5_A12_T4",
    "test262_language_statements_if_S12_5_A1_T1",
    "test262_language_statements_if_S12_5_A1_T2",
    "test262_language_expressions_strict_equals_S11_9_4_A3",
    "test262_language_expressions_strict_equals_S11_9_4_A4_2",
    "test262_language_expressions_strict_equals_S11_9_4_A4_3",
    "test262_language_expressions_strict_equals_S11_9_4_A5",
    "test262_language_expressions_strict_equals_S11_9_4_A6_2",
];

fn main() {
    let args: Vec<String> = env::args().collect();
    let binary = args[0].clone();

    if args.len() < 2 {
        run_all(&binary);
        return;
    }

    match args[1].as_str() {
        "--list" => {
            for test in ALL_TESTS {
                println!("{}", test);
            }
        }
        "--all" => {
            run_all(&binary);
        }
        test_name => {
            // Child process mode: call the test function directly.
            js2rust_init();
            if !run_test_direct(test_name) {
                eprintln!("Unknown test: {}", test_name);
                eprintln!("Use --list to see available tests.");
                flush_stdout();
                js2rust_deinit();
                std::process::exit(2);
            }
            flush_stdout();
            js2rust_deinit();
        }
    }
}

/// Dispatch to a single bridge function. Returns false if test name is unknown.
/// Called directly in child process mode (no further spawning).
#[allow(clippy::let_unit_value)]
fn run_test_direct(test_name: &str) -> bool {
    match test_name {
        "test262_language_expressions_addition_S11_6_1_A3_1_T1_3" => {
            let _ = test262_language_expressions_addition_S11_6_1_A3_1_T1_3();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T1" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T1();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T2" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T2();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T3" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T3();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T4" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T4();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T5" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T5();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T6" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T6();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T7" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T7();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T8" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T8();
            true
        }
        "test262_language_expressions_addition_S11_6_1_A4_T9" => {
            let _ = test262_language_expressions_addition_S11_6_1_A4_T9();
            true
        }
        "test262_language_expressions_multiplication_line_terminator" => {
            let _ = test262_language_expressions_multiplication_line_terminator();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A3_T1_4" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A3_T1_4();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T1_1" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T1_1();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T1_2" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T1_2();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T2" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T2();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T3" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T3();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T4" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T4();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T5" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T5();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T6" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T6();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T7" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T7();
            true
        }
        "test262_language_expressions_multiplication_S11_5_1_A4_T8" => {
            let _ = test262_language_expressions_multiplication_S11_5_1_A4_T8();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A3_T1_4" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A3_T1_4();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T1" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T1();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T2" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T2();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T3" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T3();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T4" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T4();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T5" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T5();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T6" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T6();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T7" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T7();
            true
        }
        "test262_language_expressions_subtraction_S11_6_2_A4_T8" => {
            let _ = test262_language_expressions_subtraction_S11_6_2_A4_T8();
            true
        }
        "test262_language_expressions_division_line_terminator" => {
            let _ = test262_language_expressions_division_line_terminator();
            true
        }
        "test262_language_expressions_division_no_magic_asi" => {
            let _ = test262_language_expressions_division_no_magic_asi();
            true
        }
        "test262_language_expressions_division_S11_5_2_A3_T1_4" => {
            let _ = test262_language_expressions_division_S11_5_2_A3_T1_4();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T1_1" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T1_1();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T1_2" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T1_2();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T10" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T10();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T2" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T2();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T3" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T3();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T4" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T4();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T5" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T5();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T6" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T6();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T8" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T8();
            true
        }
        "test262_language_expressions_division_S11_5_2_A4_T9" => {
            let _ = test262_language_expressions_division_S11_5_2_A4_T9();
            true
        }
        "test262_language_statements_if_empty_statement" => {
            let _ = test262_language_statements_if_empty_statement();
            true
        }
        "test262_language_statements_if_S12_5_A1_1_T1" => {
            let _ = test262_language_statements_if_S12_5_A1_1_T1();
            true
        }
        "test262_language_statements_if_S12_5_A1_1_T2" => {
            let _ = test262_language_statements_if_S12_5_A1_1_T2();
            true
        }
        "test262_language_statements_if_S12_5_A10_T1" => {
            let _ = test262_language_statements_if_S12_5_A10_T1();
            true
        }
        "test262_language_statements_if_S12_5_A10_T2" => {
            let _ = test262_language_statements_if_S12_5_A10_T2();
            true
        }
        "test262_language_statements_if_S12_5_A12_T1" => {
            let _ = test262_language_statements_if_S12_5_A12_T1();
            true
        }
        "test262_language_statements_if_S12_5_A12_T2" => {
            let _ = test262_language_statements_if_S12_5_A12_T2();
            true
        }
        "test262_language_statements_if_S12_5_A12_T3" => {
            let _ = test262_language_statements_if_S12_5_A12_T3();
            true
        }
        "test262_language_statements_if_S12_5_A12_T4" => {
            let _ = test262_language_statements_if_S12_5_A12_T4();
            true
        }
        "test262_language_statements_if_S12_5_A1_T1" => {
            let _ = test262_language_statements_if_S12_5_A1_T1();
            true
        }
        "test262_language_statements_if_S12_5_A1_T2" => {
            let _ = test262_language_statements_if_S12_5_A1_T2();
            true
        }
        "test262_language_expressions_strict_equals_S11_9_4_A3" => {
            let _ = test262_language_expressions_strict_equals_S11_9_4_A3();
            true
        }
        "test262_language_expressions_strict_equals_S11_9_4_A4_2" => {
            let _ = test262_language_expressions_strict_equals_S11_9_4_A4_2();
            true
        }
        "test262_language_expressions_strict_equals_S11_9_4_A4_3" => {
            let _ = test262_language_expressions_strict_equals_S11_9_4_A4_3();
            true
        }
        "test262_language_expressions_strict_equals_S11_9_4_A5" => {
            let _ = test262_language_expressions_strict_equals_S11_9_4_A5();
            true
        }
        "test262_language_expressions_strict_equals_S11_9_4_A6_2" => {
            let _ = test262_language_expressions_strict_equals_S11_9_4_A6_2();
            true
        }
        _ => false,
    }
}

/// Run all tests via child processes (crash isolation).
fn run_all(binary: &str) {
    let total = ALL_TESTS.len();
    let mut passed = 0usize;
    let mut failed = 0usize;
    let mut errors = 0usize;
    let mut failures: Vec<(String, String)> = Vec::new();

    for (i, test) in ALL_TESTS.iter().enumerate() {
        flush_stdout();

        let result = Command::new(binary).arg(test).output();

        match result {
            Ok(out) => {
                if out.status.success() {
                    passed += 1;
                    eprintln!("[{}/{}] {} ... PASS", i + 1, total, test);
                } else {
                    let stderr = String::from_utf8_lossy(&out.stderr);
                    let first_line = stderr.lines().next().unwrap_or("unknown");
                    failed += 1;
                    eprintln!("[{}/{}] {} ... FAIL ({})", i + 1, total, test, first_line);
                    failures.push((test.to_string(), stderr.to_string()));
                }
            }
            Err(e) => {
                errors += 1;
                eprintln!("[{}/{}] {} ... ERROR (spawn: {})", i + 1, total, test, e);
            }
        }
    }

    // Summary.
    eprintln!();
    eprintln!("=== test262 Summary ===");
    eprintln!(
        "Total: {}, Passed: {}, Failed: {}, Errors: {}",
        total, passed, failed, errors
    );

    if !failures.is_empty() {
        eprintln!();
        eprintln!("=== Failures ===");
        for (test, stderr) in &failures {
            eprintln!();
            eprintln!("  {}:", test);
            let lines: Vec<&str> = stderr.trim_end().lines().take(5).collect();
            for line in lines {
                eprintln!("    {}", line);
            }
        }
    }

    // Exit code 0 regardless - test262-project is a diagnostic tool.
}
