/// Generate a complete Zig library project from translated JS code.
use std::fs;
use std::path::Path;
use std::process::Command;

/// Project generation options
pub struct ProjectOptions {
    /// Name of the Zig library (also the output directory name)
    pub name: String,
    /// Output directory (e.g. "out")
    pub out_dir: String,
    /// The translated Zig source code (from codegen) — for single-file mode
    pub lib_code: String,
    /// Per-file Zig source: Vec of (module_name, zig_code).
    /// When non-empty, each entry is written as `{name}.zig`, and lib.zig
    /// becomes a thin orchestrator that imports all per-file modules.
    pub per_file_code: Vec<(String, String)>,
    /// Export names that should be re-exported from lib.zig (external only).
    /// Only used in per-file mode. Maps export name → source module name.
    pub external_exports: Vec<(String, String)>,
    /// Auto-generated test code (from testgen)
    pub test_code: String,
    /// Runtime source directory (relative to project root, e.g. "runtime")
    pub runtime_dir: Option<String>,
    /// Host function extern "c" declarations (from host::HostFnRegistry)
    pub host_header: String,
    /// Async host function wrapper code (generated by host::HostFnRegistry)
    pub async_host_wrappers: String,
}

/// Generate the full Zig library project.
pub fn generate(opts: &ProjectOptions) -> Result<(), String> {
    let project_dir = Path::new(&opts.out_dir).join(&opts.name);
    let src_dir = project_dir.join("src");

    // Create directories
    fs::create_dir_all(&src_dir).map_err(|e| format!("create {}: {}", project_dir.display(), e))?;

    // 1. build.zig.zon - first pass without fingerprint
    let zon_path = project_dir.join("build.zig.zon");
    let zon_no_fp = generate_zon(&opts.name, None);
    fs::write(&zon_path, &zon_no_fp)
        .map_err(|e| format!("write build.zig.zon: {}", e))?;

    // 2. build.zig
    let build_zig = generate_build_zig(&opts.name);
    fs::write(project_dir.join("build.zig"), build_zig)
        .map_err(|e| format!("write build.zig: {}", e))?;

    // 3. Write per-file .zig files (if multi-file mode) + lib.zig
    if !opts.per_file_code.is_empty() {
        // Multi-file mode: write each per-file module
        for (mod_name, zig_code) in &opts.per_file_code {
            let mod_zig = generate_module_zig(mod_name, zig_code);
            let mod_path = src_dir.join(format!("{}.zig", mod_name));
            fs::write(&mod_path, mod_zig)
                .map_err(|e| format!("write {}.zig: {}", mod_path.display(), e))?;
        }

        // Generate orchestrator lib.zig
        let lib_zig = generate_orchestrator_lib(
            &opts.name,
            &opts.per_file_code,
            &opts.external_exports,
            &opts.test_code,
            &opts.host_header,
            &opts.async_host_wrappers,
        );
        fs::write(src_dir.join("lib.zig"), lib_zig)
            .map_err(|e| format!("write lib.zig: {}", e))?;
    } else {
        // Single-file mode: traditional monolithic output
        let lib_zig = generate_lib_zig(&opts.lib_code, &opts.test_code, &opts.host_header, &opts.async_host_wrappers);
        fs::write(src_dir.join("lib.zig"), lib_zig)
            .map_err(|e| format!("write lib.zig: {}", e))?;
    }

    // 3.5 src/host.zig — host function extern "c" declarations
    if !opts.host_header.is_empty() {
        fs::write(src_dir.join("host.zig"), &opts.host_header)
            .map_err(|e| format!("write host.zig: {}", e))?;
    }

    // 4. Copy runtime/ if it exists
    if let Some(ref rt_dir) = opts.runtime_dir {
        let rt_src = Path::new(rt_dir);
        if rt_src.exists() && rt_src.is_dir() {
            let rt_dst = src_dir.join("js_runtime");
            if rt_dst.exists() {
                fs::remove_dir_all(&rt_dst).ok();
            }
            copy_dir_recursive(rt_src, &rt_dst)?;
        }
    }

    // 5. Auto-compute fingerprint via zig build
    if let Some(fp) = compute_fingerprint(&project_dir) {
        let zon_with_fp = generate_zon(&opts.name, Some(&fp));
        fs::write(&zon_path, zon_with_fp)
            .map_err(|e| format!("write build.zig.zon (with fingerprint): {}", e))?;
    }

    Ok(())
}

/// Run `zig build` in the project directory to get the suggested fingerprint.
fn compute_fingerprint(project_dir: &Path) -> Option<String> {
    let output = Command::new("zig")
        .arg("build")
        .current_dir(project_dir)
        .output()
        .ok()?;

    let stderr = String::from_utf8_lossy(&output.stderr);
    // Parse: "suggested value: 0x8f0f7e479be9961b"
    let prefix = "suggested value: ";
    if let Some(pos) = stderr.find(prefix) {
        let after = &stderr[pos + prefix.len()..];
        let fp = after.split_whitespace().next()?;
        // Validate it looks like 0xHEX
        if fp.starts_with("0x") && fp.len() == 18 {
            return Some(fp.to_string());
        }
    }
    None
}

fn generate_zon(name: &str, fingerprint: Option<&str>) -> String {
    let fp_line = match fingerprint {
        Some(fp) => format!("    .fingerprint = {},\n", fp),
        None => String::new(),
    };
    format!(
        r#".{{
    .name = .{name},
{fp_line}    .version = "0.1.0",
    .minimum_zig_version = "0.16.0",
    .paths = .{{"src", "build.zig", "build.zig.zon"}},
    .dependencies = .{{}},
}}
"#,
        name = name,
        fp_line = fp_line
    )
}

pub fn generate_build_zig(lib_name: &str) -> String {
    format!(
        r#"const std = @import("std");

pub fn build(b: *std.Build) void {{
    const target = b.standardTargetOptions(.{{}});
    const optimize = b.standardOptimizeOption(.{{}});

    const lib_mod = b.createModule(.{{
        .root_source_file = b.path("src/lib.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    }});

    // Build as static library with bundled compiler-rt.
    // Uses rust-lld (LLVM linker) at final link time to handle COMDAT sections
    // that MSVC link.exe cannot parse from Zig-generated COFF objects.
    const lib = b.addLibrary(.{{
        .name = "{name}",
        .linkage = .static,
        .root_module = lib_mod,
    }});
    lib.bundle_compiler_rt = true;
    b.installArtifact(lib);

    // Test step
    const tests = b.addTest(.{{
        .root_module = lib_mod,
    }});
    const run_tests = b.addRunArtifact(tests);
    const test_step = b.step("test", "Run all library tests");
    test_step.dependOn(&run_tests.step);
}}
"#,
        name = lib_name
    )
}

fn generate_lib_zig(translated_code: &str, test_code: &str, host_header: &str, async_wrappers: &str) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by js2rust\n");
    out.push_str("const std = @import(\"std\");\n");
    out.push_str("const builtin = @import(\"builtin\");\n");
    out.push_str("const Io = std.Io;\n");
    out.push_str("const Allocator = std.mem.Allocator;\n");
    out.push('\n');
    out.push_str("// Global allocator for generated code\n");
    out.push_str("const js_allocator = @import(\"js_runtime/js_allocator.zig\");\n");
    out.push('\n');
    out.push_str("// Tier-3 runtime library imports\n");
    out.push_str("const js_string = @import(\"js_runtime/js_string.zig\");\n");
    out.push_str("const js_console = @import(\"js_runtime/js_console.zig\");\n");
    out.push_str("const js_json = @import(\"js_runtime/js_json.zig\");\n");
    out.push_str("const js_array = @import(\"js_runtime/js_array.zig\");\n");
    out.push_str("const js_object = @import(\"js_runtime/js_object.zig\");\n");
    out.push_str("const js_number = @import(\"js_runtime/js_number.zig\");\n");
    out.push_str("const js_date = @import(\"js_runtime/js_date.zig\");\n");
    out.push_str("const js_error = @import(\"js_runtime/js_error.zig\");\n");
    out.push_str("const js_map = @import(\"js_runtime/js_map.zig\");\n");
    out.push_str("const js_set = @import(\"js_runtime/js_set.zig\");\n");
    out.push_str("const js_regexp = @import(\"js_runtime/js_regexp.zig\");\n");
    out.push_str("const js_uri = @import(\"js_runtime/js_uri.zig\");\n");
    out.push_str("const JsValue = @import(\"js_runtime/jsvalue.zig\").JsValue;\n");
    out.push('\n');

    // Host function declarations (if any)
    if !host_header.is_empty() {
        // The host_header is the full content of host.zig — import it
        out.push_str("// Tier-4 host functions (Rust via C ABI)\n");
        out.push_str("const host = @import(\"host.zig\");\n");
        out.push('\n');
    }

    // Windows stub: LdrRegisterDllNotification is referenced by
    // std.debug.SelfInfo.Windows but ntdll.lib may not export it in all SDKs.
    // Provide a stub that returns success (no DLL tracking needed for static lib).
    out.push_str("const windows = std.os.windows;\n");
    out.push_str("pub export fn LdrRegisterDllNotification(\n");
    out.push_str("    Flags: windows.ULONG,\n");
    out.push_str("    NotificationFunction: ?*const anyopaque,\n");
    out.push_str("    Context: ?*anyopaque,\n");
    out.push_str("    Cookie: *?*anyopaque,\n");
    out.push_str(") callconv(.c) windows.NTSTATUS {\n");
    out.push_str("    _ = Flags;\n");
    out.push_str("    _ = NotificationFunction;\n");
    out.push_str("    _ = Context;\n");
    out.push_str("    Cookie.* = @ptrFromInt(1);\n");
    out.push_str("    return .SUCCESS;\n");
    out.push_str("}\n\n");

    // Async host function wrappers (if any)
    if !async_wrappers.is_empty() {
        out.push_str(async_wrappers);
        out.push('\n');
    }

    out.push_str(translated_code);

    // Append test blocks
    if !test_code.trim().is_empty() {
        out.push('\n');
        out.push_str(test_code);
    }
    out
}

fn generate_module_zig(mod_name: &str, zig_code: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("// Auto-generated from {}.js\n", mod_name));
    out.push_str("const std = @import(\"std\");\n");
    out.push_str("const js_allocator = @import(\"js_runtime/js_allocator.zig\");\n");
    // Only add Io import if the code uses async (contains "Io" or "io: Io")
    if zig_code.contains("io: Io") || zig_code.contains("Io,") {
        out.push_str("const Io = std.Io;\n");
    }
    out.push('\n');
    out.push_str(zig_code);
    out
}

/// Generate the orchestrator lib.zig for multi-file mode.
/// Imports all per-file modules, re-exports external exports, includes test blocks.
fn generate_orchestrator_lib(
    name: &str,
    per_file_code: &[(String, String)],
    external_exports: &[(String, String)],
    test_code: &str,
    host_header: &str,
    async_wrappers: &str,
) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by js2rust (orchestrator)\n");
    out.push_str("const std = @import(\"std\");\n");
    out.push_str("const builtin = @import(\"builtin\");\n");
    out.push_str("const Io = std.Io;\n");
    out.push_str("const Allocator = std.mem.Allocator;\n");
    out.push('\n');
    out.push_str("// Tier-3 runtime library imports\n");
    out.push_str("const js_string = @import(\"js_runtime/js_string.zig\");\n");
    out.push_str("const js_console = @import(\"js_runtime/js_console.zig\");\n");
    out.push_str("const js_json = @import(\"js_runtime/js_json.zig\");\n");
    out.push_str("const js_array = @import(\"js_runtime/js_array.zig\");\n");
    out.push_str("const js_object = @import(\"js_runtime/js_object.zig\");\n");
    out.push_str("const js_number = @import(\"js_runtime/js_number.zig\");\n");
    out.push_str("const js_date = @import(\"js_runtime/js_date.zig\");\n");
    out.push_str("const js_error = @import(\"js_runtime/js_error.zig\");\n");
    out.push_str("const js_map = @import(\"js_runtime/js_map.zig\");\n");
    out.push_str("const js_set = @import(\"js_runtime/js_set.zig\");\n");
    out.push_str("const js_regexp = @import(\"js_runtime/js_regexp.zig\");\n");
    out.push_str("const JsValue = @import(\"js_runtime/jsvalue.zig\").JsValue;\n");
    out.push('\n');
    out.push_str("// Global allocator for generated code\n");
    out.push_str("const js_allocator = @import(\"js_runtime/js_allocator.zig\");\n");
    out.push('\n');

    // Host function declarations (if any)
    if !host_header.is_empty() {
        out.push_str("// Tier-4 host functions (Rust via C ABI)\n");
        out.push_str("const host = @import(\"host.zig\");\n");
        out.push('\n');
    }

    // Windows stub
    out.push_str("const windows = std.os.windows;\n");
    out.push_str("pub export fn LdrRegisterDllNotification(\n");
    out.push_str("    Flags: windows.ULONG,\n");
    out.push_str("    NotificationFunction: ?*const anyopaque,\n");
    out.push_str("    Context: ?*anyopaque,\n");
    out.push_str("    Cookie: *?*anyopaque,\n");
    out.push_str(") callconv(.c) windows.NTSTATUS {\n");
    out.push_str("    _ = Flags;\n");
    out.push_str("    _ = NotificationFunction;\n");
    out.push_str("    _ = Context;\n");
    out.push_str("    Cookie.* = @ptrFromInt(1);\n");
    out.push_str("    return .SUCCESS;\n");
    out.push_str("}\n\n");

    // Async host function wrappers (if any)
    if !async_wrappers.is_empty() {
        out.push_str(async_wrappers);
        out.push('\n');
    }

    // Per-file module imports
    out.push_str("// Per-file module imports\n");
    for (mod_name, _) in per_file_code {
        out.push_str(&format!("const {} = @import(\"{}.zig\");\n", mod_name, mod_name));
    }
    out.push('\n');

    // --- Global initialization / deinitialization ---
    out.push_str("/// Initialize the global allocator used by all generated functions.\n");
    out.push_str("pub fn init_js2rust(allocator: std.mem.Allocator) void {\n");
    out.push_str("    js_allocator.setGlobalAllocator(allocator);\n");
    out.push_str("}\n\n");
    out.push_str("/// Release global resources allocated via init_js2rust.\n");
    out.push_str("pub fn deinit_js2rust() void {}\n\n");

    // Re-export all exports so lib.zig test blocks can reference them directly
    if !external_exports.is_empty() {
        out.push_str("// Re-export all public exports\n");
        let mut exported: std::collections::HashSet<&str> = std::collections::HashSet::new();
        for (exp_name, mod_name) in external_exports {
            if exported.insert(exp_name) {
                out.push_str(&format!(
                    "pub const {exp} = {mod}.{exp};\n",
                    exp = exp_name,
                    mod = mod_name
                ));
            }
        }
        out.push('\n');
    }

    // Append test blocks
    if !test_code.trim().is_empty() {
        out.push_str(test_code);
        out.push('\n');
    }

    _ = name; // silence unused warning
    out
}

/// Recursively copy a directory
fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<(), String> {
    fs::create_dir_all(dst).map_err(|e| format!("create dir {}: {}", dst.display(), e))?;

    for entry in fs::read_dir(src).map_err(|e| format!("read dir {}: {}", src.display(), e))? {
        let entry = entry.map_err(|e| format!("read entry: {}", e))?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());

        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else if src_path.is_file() {
            fs::copy(&src_path, &dst_path)
                .map_err(|e| format!("copy {}: {}", src_path.display(), e))?;
        }
    }

    Ok(())
}
