[project]
js_files = [
    "js_src/app.js",
    "js_src/phase5.js",
    "js_src/test_throw.js",
    "js_src/phase_memory.js",
    "js_src/phase6.js",
    "js_src/test_classes.js",
    "js_src/test_static_fields.js",
    "js_src/test_dynamic_index.js",
]

[build]
run_zig_build = true
