[project]
js_dir = "js_src"
js_files = [
    "app.js",
    "phase5.js",
    "test_throw.js",
    "phase_memory.js",
    "phase6.js",
    "test_classes.js",
    "test_static_fields.js",
    "test_dynamic_index.js",
    "test_optional.js",
    "for_in_struct.js",
]

[build]
run_zig_build = true
